[package]
name = "wezterm-build-error"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = { version = "0.10", features=["vendored"] }
git2 = { version = "0.16", default-features = false, features = ["https"] }
